src/main/java/com/ttAX/model/Messages.java
package com.ttAX.model;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
//import java.security.Timestamp;
import java.util.Date;
//import java.sql.Timestamp;

@Entity
public class Messages {

    private int idMessage;
    private String sender;
    private String recipient;
    private Date dateval;
    private String theme;
    private String text;

    @Id
    @Column(name = "id_message", nullable = false)
    @GenericGenerator(name="generator", strategy="increment")
    @GeneratedValue(generator="generator")
    public int getIdMessage() {
        return idMessage;
    }

    public void setIdMessage(int idMessage) {
        this.idMessage = idMessage;
    }

    @Basic
    @Column(name = "sender", nullable = true, length = 255)
    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    @Basic
    @Column(name = "recipient", nullable = true, length = 255)
    public String getRecipient() {
        return recipient;
    }

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    @CreationTimestamp
    @Column(name = "dateval", nullable = true)
    public Date getDate() {
        return dateval;
    }

    public void setDate(Date dateval) {
        this.dateval = dateval;
    }

    @Basic
    @Column(name = "theme", nullable = true, length = 255)
    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    @Basic
    @Column(name = "text", nullable = true, length = 255)
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Messages messages = (Messages) o;

        if (idMessage != messages.idMessage) return false;
        if (sender != null ? !sender.equals(messages.sender) : messages.sender != null) return false;
        if (recipient != null ? !recipient.equals(messages.recipient) : messages.recipient != null) return false;
        if (dateval != null ? !dateval.equals(messages.dateval) : messages.dateval != null) return false;
        if (theme != null ? !theme.equals(messages.theme) : messages.theme != null) return false;
        if (text != null ? !text.equals(messages.text) : messages.text != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = idMessage;
        result = 31 * result + (sender != null ? sender.hashCode() : 0);
        result = 31 * result + (recipient != null ? recipient.hashCode() : 0);
        result = 31 * result + (dateval != null ? dateval.hashCode() : 0);
        result = 31 * result + (theme != null ? theme.hashCode() : 0);
        result = 31 * result + (text != null ? text.hashCode() : 0);
        return result;
    }
}

src/main/java/com/ttAX/controller/AjaxController.java
package com.ttAX.controller;

import com.ttAX.dao.UserDAOImpl;
import com.ttAX.model.Addressbook;
import com.ttAX.model.Messages;
import com.ttAX.model.Users;

import com.ttAX.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@Controller
public class AjaxController {

    private UserDAOImpl userDAOImpl = new UserDAOImpl();
    private Users user = new Users();

    private UserService userService;

    @Autowired(required=true)
    @Qualifier(value = "userService")
    public void setUserService(UserService userService){
        this.userService = userService;
    }

    @RequestMapping(value= "/checkAJAX", method = RequestMethod.POST)
    public void checkUser(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        Addressbook addressbook = new Addressbook();

        try {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            String login = auth.getName();
            String recipient = request.getParameter("login");
            user = userService.findLogin(recipient);
//            addressbook = userService.findUserBook(login,recipient);
            if (user==null) {
                out.println("<font color=red>not found</font>");
//            }else if (addressbook!=null){
//                out.println("<font color=red>contact already</font>");
                } else {
                out.println("<font color=green>added</font>");
                addressbook.setLogin(login);
                addressbook.setRecipient(recipient);
                userDAOImpl.addUserBook(addressbook);
            }
            out.println();

        } catch (Exception ex) {
            out.println("Error ->" + ex.getMessage());
        } finally {
            out.close();
        }
    }

    @RequestMapping(value= "/AddressBook", method = RequestMethod.POST)
    public void addressBook(HttpServletRequest request, HttpServletResponse response, Addressbook addressbook, Model model) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        model.addAttribute("addressBook", new Addressbook());

        try {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            String login = auth.getName();
            model.addAttribute("listAddressBook", this.userService.listUserBook(login));

        } catch (Exception ex) {
            out.println("Error ->" + ex.getMessage());
        } finally {
            out.close();
        }
    }

    @RequestMapping(value= "/changePassword", method = RequestMethod.POST)
    public void changePassword(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        try {
            user = userDAOImpl.findLogin(auth.getName());
            user.setPassword(request.getParameter("newpass"));
            user.setConfrimpassword(request.getParameter("newpass"));
            userDAOImpl.updateUser(user);
            out.println("<font color=green><b>"+"</b> Password successfully changed");
        } catch (Exception ex) {
            out.println("Error ->" + ex.getMessage());
        } finally {
            out.close();
        }
    }

    @RequestMapping(value= "/checkPassword", method = RequestMethod.POST)
    public void checkPassword(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        try {
            String pass = request.getParameter("password");
            String newPass = request.getParameter("newpass");

            user = userDAOImpl.findLogin(auth.getName());
            if (!user.getPassword().equals(pass)){
                out.println("<font color=red><b>"+"</b> Passwords do not match");
                return;
            }
            if (pass.equals(newPass)){
                out.println("<font color=red><b>"+"</b> Passwords match");
                return;
            }
        } catch (Exception ex) {
            out.println("Error ->" + ex.getMessage());
        } finally {
            out.close();
        }
    }

    @RequestMapping(value= "/sendMessage", method = RequestMethod.POST)
    public void sendMessage(HttpServletRequest request, HttpServletResponse response, Messages message, Addressbook addressbook) throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String login = auth.getName();

        try {

            String sendText = request.getParameter("sendText");
            String theme = request.getParameter("theme");
            String nameRecipient = request.getParameter("nameRecipient");

            message.setText(sendText);
            message.setTheme(theme);
            message.setSender(login);
            message.setRecipient(nameRecipient);
            userService.sendMessage(message);

        } catch (Exception ex) {
            out.println("Error ->" + ex.getMessage());
        } finally {
            out.close();
        }
    }

}

src/main/java/com/ttAX/controller/UserController.java
package com.ttAX.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import com.ttAX.model.Users;
import com.ttAX.model.Roles;
import com.ttAX.service.UserService;




@Controller
public class UserController {

    private UserService userService;
    private final String loginMessage = "Login already exist";

    @Autowired(required=true)
    @Qualifier(value = "userService")
    public void setUserService(UserService userService){
        this.userService = userService;
    }

    @RequestMapping(value = "/users", method = RequestMethod.GET)
    public String listUsers(Model model) {
        model.addAttribute("role", new Roles());
        model.addAttribute("user", new Users());
        model.addAttribute("listUsers", this.userService.listUsers());
        return "user";
    }

    @RequestMapping(value= "/user/add", method = RequestMethod.POST)
    public String addUser(@ModelAttribute("user") @Valid Users u, BindingResult bindingResult,HttpServletRequest request, Model model){
        if (u.getLogin().isEmpty()){
            model.addAttribute("listUsers", this.userService.listUsers());
            return "user";
        }
        if( bindingResult.hasErrors()) {
            if (userService.findLogin(u.getLogin())!=null){
                request.setAttribute("message", loginMessage);
            }
            model.addAttribute("listUsers", this.userService.listUsers());
            return "user";
        }
        if (userService.findLogin(u.getLogin())!=null){
            request.setAttribute("message", loginMessage);
            model.addAttribute("listUsers", this.userService.listUsers());
            return "user";
        }

        Roles r = new Roles();
        r.setLogin(u.getLogin());
        r.setRole("user");
        u.setEnabled(true);
        this.userService.regUser(u,r);

        return "redirect:/users";
    }

    @RequestMapping(value= "/regUser", method = RequestMethod.POST)
    public String regUser(@ModelAttribute("user") @Valid Users u, BindingResult bindingResult, HttpServletRequest request){
        if (u.getLogin().isEmpty()){
            return "registerPage";
        }
        if( bindingResult.hasErrors()) {
            if (userService.findLogin(u.getLogin())!=null){
                request.setAttribute("message", loginMessage);
            }
            return "registerPage";
        }
        if (userService.findLogin(u.getLogin())!=null){
            request.setAttribute("message", loginMessage);
            return "registerPage";
        }

        Roles r = new Roles();
        r.setLogin(u.getLogin());
        r.setRole("user");
        u.setEnabled(true);
        this.userService.regUser(u,r);
        return "redirect:/login";
    }

    @RequestMapping("/edit/{id}")
    public String editUserPage(@PathVariable("id") int id, Model model){
        model.addAttribute("user", this.userService.getUserById(id));
        model.addAttribute("role", this.userService.getRoleById(id));
        model.addAttribute("listUsers", this.userService.listUsers());
        return "user";
    }

    @RequestMapping(value= "/user/edit", method = RequestMethod.POST)
    public String editRole(@ModelAttribute("user") Users u, @RequestParam("roles.role") String roleForm,Roles r, Model model){
        model.addAttribute("listUsers", this.userService.listUsers());

        r.setIdRole(u.getId());
        u = userService.getUserById(u.getId());
        r.setLogin(u.getLogin());
        r.setRole(roleForm);
        this.userService.updateRole(r);
        return "redirect:/users";
    }

    @RequestMapping("/remove/{id}")
    public String removeUser(@PathVariable("id") int id){
        this.userService.removeUser(id);
        return "redirect:/users";
    }


    @RequestMapping(value = "/registrationPage", method = RequestMethod.GET)
    public String registerPage(Model model) {
        model.addAttribute("user", new Users());
        return "registerPage";
    }

}

web/WEB-INF/views/403Page.jsp
<%@page session="false"%>
<%@ page contentType="text/html;charset=UTF-8" %>

<html>
<head>
    <title>Access Denied</title>
</head>
<body>
<jsp:include page="menu.jsp"/>

<h3 style="color:red;">${message}</h3>
</body>
</html>

web/WEB-INF/views/AJAX.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%--<!DOCTYPE html>--%>
<link  href="<c:url value="/resources/style.css"/>" rel="stylesheet" type="text/css">
<%--<script src="<c:url value="/resources/popup.js" />" type="text/javascript"></script>--%>
<%--<script src="<c:url value="/resources/changePassword.js" />" type="text/javascript"></script>--%>
<script src="<c:url value="/resources/jquery.js" />" type="text/javascript"></script>

<html>
<body>
<jsp:include page="menu.jsp"/>

<button id="myBtn">Open Modal</button>
    <div id="myModal" class="modal">

        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Изменить пароль</h3>
            <table method="post" name="password-form" id="form-password">
                <label>Current Password:</label> <br>
                <input type="password" name="password" id="password" value="" size="32" />
                <br>
                <br>
                <label>New Password:</label> <br>
                <input type="password" name="new-password" id="new-password" value="" size="32" />
                <br>
                <br>
                <label>Re-Enter Password:</label> <br>
                <input type="password" name="password-check" id="password-check" value="" size="32" />
                <br>
                <br>
                <input type="submit" value="Submit" id="passsubmit">
            </table>
        </div>

    </div>

<script>
//    Modal Window START
    var modal = document.getElementById('myModal');
    var btn = document.getElementById("myBtn");
    var span = document.getElementsByClassName("close")[0];
    btn.onclick = function() {
        modal.style.display = "block";
    }
    span.onclick = function() {
        modal.style.display = "none";
    }
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
//    Modal Window END

    $(function(){
        $("#passsubmit").click(function(){
            $(".error").hide();
            var hasError = false;
            var password = $("#password").val();
            var newpass = $("#new-password").val();
            var checkVal = $("#password-check").val();
            if (newpass == '') {
                $("#new-password").after('<span class="error"> Please enter a password.</span>');
                hasError = true;
            } else if (checkVal == '') {
                $("#password-check").after('<span class="error"> Please re-enter your password.</span>');
                hasError = true;
            } else if (newpass != checkVal ) {
                $("#password-check").after('<span class="error"> Passwords do not match.</span>');
                hasError = true;
            }

            if(hasError == true) {return false;}

            if(hasError == false) {
                $.ajax({
                    type: "POST",
                    url: "changePassword",
                    data: {newpass:newpass},
                    success: function(msg){
                        $(".status").ajaxComplete(function(event, request, settings){
                            $(".status").html(msg);
                        });
                    }
                });
            };
        });

    });

</script>
</body>
</html>

web/WEB-INF/views/adminPage.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page session="true"%>
<%@ page contentType="text/html;charset=UTF-8" %>

<html>
<head>
    <title>${title}</title>
</head>
<body>
<jsp:include page="menu.jsp" />

<h2>Admin Page</h2>


<h3>Welcome : ${pageContext.request.userPrincipal.name}</h3>

<%--<b>This is protected page!</b>--%>
</body>
</html>

web/WEB-INF/views/homePage.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@page session="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%--<%@ taglib prefix="form" uri="http://java.sun.com/jsf/html" %>--%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<link  href="<c:url value="/resources/style.css"/>" rel="stylesheet" type="text/css">
<script src="<c:url value="/resources/jquery.js" />" type="text/javascript"></script>

<html>
<head>
    <title>${title}</title>
</head>
<body>

<jsp:include page="menu.jsp"/>

<c:if test="${pageContext.request.userPrincipal.name == null}">
    <h3>Войдите или зарегистрируйтесь.</h3>
</c:if>

<c:if test="${pageContext.request.userPrincipal.name != null}">

    <table>
        <tr>
            <td>Текущий пользователь : </td>
            <td style="font-weight:bold">${pageContext.request.userPrincipal.name}</td>
            <%--<td><form:form action="/home/book" method="get" ><input type="submit" value="адрессная книга"></form:form></td>--%>
            <td><button id="myBtn">изменить пароль</button>&nbsp;<span class="status"></span></td>
        </tr>
    </table>
    &nbsp;
    <%--<form:form action="/ttAX/home/book" method="get" ><input type="submit" value="Адрессная книга"></form:form>--%>
    <a href="${pageContext.request.contextPath}/book">Адрессная книга</a>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Изменить пароль</h3>
            <table method="post" name="password-form" id="form-password">
                <%--<label>Current Password:</label> <br>--%>
                <%--<input type="password" name="password" id="password" value="" size="32" />--%>
                    <%--<br>--%>
                    <%--<br>--%>
                <label>New Password:</label> <br>
                <input type="password" name="new-password" id="new-password" value="" size="32" />
                    <br>
                    <br>
                <label>Re-Enter Password:</label> <br>
                <input type="password" name="password-check" id="password-check" value="" size="32" />
                    <br>
                    <br>
                <input type="submit" value="Submit" id="passsubmit">
            </table>
        </div>
    </div>

    <script>
        //        Window START
        var modal = document.getElementById('myModal');
        var btn = document.getElementById("myBtn");
        var span = document.getElementsByClassName("close")[0];
        btn.onclick = function() {
            modal.style.display = "block";
        }
        span.onclick = function() {
            modal.style.display = "none";
        }
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
        //        Window END

        $(function(){
            $("#passsubmit").click(function(){
                $(".error").hide();
                var hasError = false;
                var password = $("#password").val();
                var newpass = $("#new-password").val();
                var checkVal = $("#password-check").val();
                if (newpass == '') {
                    $("#password").after('<span class="error"> Please enter current password.</span>');
                    hasError = true;
                }
                if (newpass == '') {
                    $("#new-password").after('<span class="error"> Please enter new password.</span>');
                    hasError = true;
                } else if (checkVal == '') {
                    $("#password-check").after('<span class="error"> Please re-enter your password.</span>');
                    hasError = true;
                } else if (newpass != checkVal ) {
                    $("#password-check").after('<span class="error"> Passwords do not match.</span>');
                    hasError = true;
                }

                if(hasError == true) {
                    return false;
                }

                if(hasError == false) {
                    $(".status").html("<img src='/resources/loading.gif'><font color=gray> Checking availability...</font>");
                    $.ajax({
                        type: "POST",
                        url: "changePassword",
                        data: {newpass:newpass},
                        success: function(msg){
                            $(".status").ajaxComplete(function(event, request, settings){
                                $(".status").html(msg);
                            });
                        }
                    });
                    modal.style.display = "none";
                };
            });

        });
    </script>

    <h3>Messages:</h3>

        <table id="homeTable" class="tg">
            <tr>
                <th  width="100"><a href="<c:url value='/home/sort_sender'/>">Отправитель</a></th>
            <security:authorize access="hasAnyRole('admin')">
                <th id="itemRecipient" width="100"><a href="<c:url value='/home/sort_recipient'/>">Получатель</a></th>
            </security:authorize>
                <th id="itemDate" datatype="timestamp" width="100"><a href="<c:url value='/home/sort_date'/>">Дата</a></th>
                <th id="itemTheme" width="100"><a href="<c:url value='/home/sort_theme'/>">Тема</a></th>
                <th id="itemText" width="100">Сообщение</th>
                <th width="80">Удалить сообщение</th>
            </tr>

            <c:forEach items="${listMessages}" var="messages">
            <tr>
                <td class="itemSender" align="center" >${messages.sender}</td>
            <security:authorize access="hasAnyRole('admin')">
                <td align="center">${messages.recipient}</td>
            </security:authorize>
                <td class="itemDate" align="center" >${messages.date}</td>
                <td class="itemTheme" align="center" >${messages.theme}</td>
                <td class="itemText" style="color:blue;text-decoration: underline;"><a class="infoMessage">${messages.text}</a></td>
                <td class="openButtonSend" id="openButtonSend" align="center"> <a href="<c:url value='/home/remove/${messages.idMessage}' />" >удалить</a></td>
                <%--<td align="center"><input type="button" id="openButtonSend" class="openButtonSend" onclick="myFunction()" value="написать"/></td>--%>
            </tr>
            </c:forEach>

        </table>

    <dialog id="myDialog" class="home-modal">
        <h3>Информация</h3>
        <table method="post" name="send-form" id="send-password">
            <tr>
                <td><label>Отправитель</label></td>
            </tr>
            <tr>
                <td><input type="text" name="theme" id="from" disabled="true" readonly="true" value="" size="26" /></td>
            </tr>
            <tr>
                <td><label>Тема</label></td>
            </tr>
            <tr>
                <td><input type="text" name="theme" id="theme" disabled="true" readonly="true" value="" size="26" /></td>
            </tr>
            <tr>
                <td><label>Дата</label></td>
            </tr>
            <tr>
                <td><input type="text" name="theme" id="data" disabled="true" readonly="true" value="" size="26" /></td>
            </tr>

            <tr>
                <td><label>Сообщение</label></td>
            </tr>
            <tr>
                <td><div><textarea class="writeMessages" id="readText" disabled="true" readonly="true" ></textarea></div></td>
            </tr>

            <tr>
                <td><input type="submit" value="Отправить" id="sendButton">&nbsp;<input type="submit" value="Закрыть" onclick="closeDialog()"></td>
            </tr>
        </table>
    </dialog>

    <script>

//        $("#homeTable td").click(function(){
//            var row = $(this).closest("tr");    // Find the row
//            var itemText = row.find(".itemText").text(); // Find the text
//            alert(itemText);
//        });

    function closeDialog() {
        document.getElementById("myDialog").close();
    }

//        $("#homeTable td").click(function(){
    $(".infoMessage").click(function() {

        document.getElementById("myDialog").show();

        var row = $(this).closest("tr");    // Find the row
        var itemSender = row.find(".itemSender").text(); // Find the text
        var itemDate = row.find(".itemDate").text(); // Find the text
        var itemTheme = row.find(".itemTheme").text(); // Find the text
        var itemText = row.find(".itemText").text(); // Find the text

        document.getElementById("from").setAttribute('value',itemSender);
        document.getElementById("data").setAttribute('value',itemDate);
        document.getElementById("theme").setAttribute('value',itemTheme);
        document.getElementById("readText").value = itemText;

    });

    </script>

</c:if>
</body>
</html>

web/WEB-INF/views/loginPage.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page contentType="text/html;charset=UTF-8" %>

<html>
<head><title>Авторизация</title></head>

<body>
<jsp:include page="menu.jsp" />


<%--<h2>Страница авторизации</h2>--%>
<!-- /login?error=true -->
<c:if test="${param.error == 'true'}">
    <div style="color:red;margin:10px 0px;">
        Неправильный логин или пароль!!!<br />
        <%--Reason :  ${sessionScope["SPRING_SECURITY_LAST_EXCEPTION"].message}--%>
    </div>
</c:if>

<%--<h3>Введите логин и пароль:</h3>--%>

    <form name='f' action="${pageContext.request.contextPath}/spring_security_check" method='POST'>
        <table>
            <tr>
                <td>Логин:</td>
                <td><input type='text' name='username' value=''></td>
            </tr>
            <tr>
                <td>Пароль:</td>
                <td><input type='password' name='password' /></td>
            </tr>
        </table>
        <tr>
            <td><input name="submitIn" type="submit" value="Войти"/></td>
            <%--<td> или <input name="submitUp" type="submit" value="Зарегистрироваться" formaction="register" formmethod="get" /></td>--%>
        </tr>
    </form>

</body>
</html>

web/WEB-INF/views/logoutSuccessfulPage.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title>Logout</title>
</head>
<body>
<jsp:include page="menu.jsp" />

<h2>Успешный выход!</h2>
</body>
</html>

web/WEB-INF/views/menu.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ page contentType="text/html;charset=UTF-8" %>

<div style="border: 1px solid #ccc;padding:5px;margin-bottom:20px;">

    &nbsp;
    <a href="${pageContext.request.contextPath}/home">Главная</a>

    <c:if test="${pageContext.request.userPrincipal.name == null}">

        &nbsp; | &nbsp;
        <a href="${pageContext.request.contextPath}/login">Войти</a>

    </c:if>

    <c:if test="${pageContext.request.userPrincipal.name == null}">

        &nbsp; | &nbsp;
        <a href="${pageContext.request.contextPath}/registrationPage">Зарегистрироваться</a>

    </c:if>

    <security:authorize access="hasAnyRole('admin')">

        &nbsp; | &nbsp;
        <a href="${pageContext.request.contextPath}/users">Пользователи</a>

    </security:authorize>

    <c:if test="${pageContext.request.userPrincipal.name != null}">

        &nbsp; | &nbsp;
        <a href="${pageContext.request.contextPath}/logout">Выйти</a>

    </c:if>

    <%--&nbsp; | &nbsp;--%>
    <%--<a href="${pageContext.request.contextPath}/book">Адрессная книга</a>--%>

    <%--&nbsp; | &nbsp;--%>
    <%--<a href="${pageContext.request.contextPath}/addUserAJAX">ajax</a>--%>


</div>

web/WEB-INF/views/userInfoPage.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page session="true"%>
<%@ page contentType="text/html;charset=UTF-8" %>

<html>
<head>
    <title>User Info</title>
</head>
<body>
<jsp:include page="menu.jsp" />

<%--<h2>User Info Page</h2>--%>

<h3>Текущий пользователь : ${pageContext.request.userPrincipal.name}</h3>

</body>
</html>